spring:
  application:
    name: dividend-service

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password:

  data:
    redis:
      host: localhost
      port: 6379

  jwt:
    secret: c3ByaW5nYm9vdC1wcm9qZWN0LWRpdmlkZW5kLXNlcnZpY2U=

scheduler:
  scrap:
    yahoo: "0 0 0 * * *"